/* Generated By:JavaCC: Do not edit this line. CDLParserTreeConstants.java Version 5.0 */
package com.knoll.cztools.cdl.parser;

public interface CDLParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTEXPR_OPERATOR = 1;
  public int JJTEXPR_ITERATOR = 2;
  public int JJTEXPR_COMPATIBLE = 3;
  public int JJTEXPR_CALL = 4;
  public int JJTEXPR_METHOD = 5;
  public int JJTEXPR_LITERAL = 6;
  public int JJTEXPR_EVENT = 7;
  public int JJTEXPR_EVENTSCOPE = 8;
  public int JJTEXPR_SYSTEMARGUMENT = 9;
  public int JJTEXPR_EVENTARGUMENT = 10;
  public int JJTEXPR_FOR_ALL = 11;
  public int JJTEXPR_WHERE = 12;
  public int JJTEXPR_DISTINCT = 13;
  public int JJTEXPR_TEMPLATE = 14;
  public int JJTEXPR_REFNODE = 15;
  public int JJTEXPR_PROP = 16;
  public int JJTEXPR_SYS_PROP = 17;
  public int JJTEXPR_PSNODE = 18;
  public int JJTEXPR_ARGUMENT = 19;


  public String[] jjtNodeName = {
    "void",
    "EXPR_OPERATOR",
    "EXPR_ITERATOR",
    "EXPR_COMPATIBLE",
    "EXPR_CALL",
    "EXPR_METHOD",
    "EXPR_LITERAL",
    "EXPR_EVENT",
    "EXPR_EVENTSCOPE",
    "EXPR_SYSTEMARGUMENT",
    "EXPR_EVENTARGUMENT",
    "EXPR_FOR_ALL",
    "EXPR_WHERE",
    "EXPR_DISTINCT",
    "EXPR_TEMPLATE",
    "EXPR_REFNODE",
    "EXPR_PROP",
    "EXPR_SYS_PROP",
    "EXPR_PSNODE",
    "EXPR_ARGUMENT",
  };
}
/* JavaCC - OriginalChecksum=f29ea55c5a4fd3853a1863c59a416820 (do not edit this line) */
